@Harjoitus1_HostAddress = https://localhost:7042

POST {{Harjoitus1_HostAddress}}/todoitems
Content-Type: application/json

{
  "name":"feed fish",
  "isComplete":true
}

###

GET {{Harjoitus1_HostAddress}}/todoitems

###

GET {{Harjoitus1_HostAddress}}/todoitems/1

###

PUT {{Harjoitus1_HostAddress}}/todoitems/1
Content-Type: application/json

{
  "name": "feed fish",
  "isComplete": false
}

###

DELETE {{Harjoitus1_HostAddress}}/todoitems/1

###

POST {{Harjoitus1_HostAddress}}/todoitems
Content-Type: application/json

{
  //Todo
}

###
